#MariaDB
spring:
  application:
    name: Library
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:3306/library}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: org.mariadb.jdbc.Driver
#JPA
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  thymeleaf:
    cache: false
#Mail Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SENDER_MAIL_USERNAME}
    password: ${SENDER_MAIL_PASSWORD}
#Other properties
    properties:
      mail:
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
#TLS, port 587
          starttls:
            enable: true